# Generated by Django 6.0.4 on 2026-04-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("person_id", models.AutoField(primary_key=True, serialize=False)),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=255)),
                ("occupation", models.CharField(max_length=100)),
                (
                    "membership_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("suspended", "Suspended"),
                        ],
                        max_length=20,
                    ),
                ),
                ("membership_desc", models.TextField(blank=True, null=True)),
                ("nrc", models.CharField(max_length=50)),
            ],
            options={
                "ordering": ["lastname", "firstname"],
            },
        ),
    ]
