# Generated by Django 6.0.4 on 2026-04-25 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village_banking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                ("interest_id", models.AutoField(primary_key=True, serialize=False)),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("interest_desc", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-interest_rate"],
            },
        ),
        migrations.CreateModel(
            name="Loan_Payment",
            fields=[
                (
                    "loan_payment_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField()),
                (
                    "person_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="village_banking.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("membership_id", models.AutoField(primary_key=True, serialize=False)),
                ("join_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("non-member", "Non-Member"),
                            ("treasurer", "Treasurer"),
                            ("secretary", "Secretary"),
                            ("admin", "Admin"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "person_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="village_banking.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-join_date"],
            },
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                ("loan_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "loan_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("active", "Active"),
                            ("paid", "Paid"),
                            ("defaulted", "Defaulted"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount_remaining",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("collateral_desc", models.TextField(blank=True, null=True)),
                ("loan_issue_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "membership_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="village_banking.membership",
                    ),
                ),
            ],
            options={
                "ordering": ["-loan_issue_date"],
            },
        ),
        migrations.CreateModel(
            name="Investment",
            fields=[
                ("investment_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                (
                    "investment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("monthly contribution", "Monthly Contribution"),
                            ("annual contribution", "Annual Contribution"),
                            ("loan", "Loan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "penalty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("expected_date", models.DateField()),
                (
                    "membership_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="village_banking.membership",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Penalty",
            fields=[
                ("penalty_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "penalty_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("waived", "Waived"),
                            ("overdue", "Overdue"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "person_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="village_banking.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("transaction_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("withdrawal", "Withdrawal"),
                            ("payment", "Payment"),
                            ("investment", "Investment"),
                            ("penalty", "Penalty"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "membership_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="village_banking.membership",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
