# Generated by Django 6.0.4 on 2026-04-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("village_banking", "0003_person_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="category",
            field=models.CharField(
                choices=[
                    ("monthly contribution", "Monthly Contribution"),
                    ("annual contribution", "Annual Contribution"),
                    ("loan", "Loan"),
                    ("investment", "Investment"),
                ],
                max_length=20,
            ),
        ),
    ]
